import { connectToDatabase } from '../../database/mongodb';
import dotenv from 'dotenv';
dotenv.config( { path:'../../../.env' } );

export async function POST ( req ) {
  const db = await connectToDatabase();
  const formData = await req.formData();
  const name = formData.get( 'name' );
  const email = formData.get( 'email' );
  const message = formData.get( 'message' );

  const mailjet = require( 'node-mailjet' ).apiConnect(
    process.env.MAILJET_API_KEY,
    process.env.MAILJET_API_SECRET
  );
    
  const request = mailjet.post( 'send', { version: 'v3.1' } ).request( {
    Messages: [ {
      From: {
        Email: process.env.MAILJET_API_EMAIL,
        Name: name,
      },
      To: [ {
        Email: email,
        Name: 'dear customer'
      } ],
      Subject: 'Your legacy of dead man switch',
      TextPart: 'Email content (message).',
      HtmlPart: `
                <h3>Dear customer</h3>
                <p>Here is dead man button generated by our service to make you postpone delivery of your data to your heir(s) ${message}</p>`
    } ]
  } );
  request.then( result => {
    try {
      const isStored = db.collection( 'clients' ).findOne( { email } );
      if( !isStored ) {
        const result = db.collection( 'clients' ).insertOne( {
          name: email.split( '@' )[0].replace( /[_\.-]/g, ' ' ),
          email,
          message
        } );
            
        console.log( JSON.stringify( result ) );
      }
    } catch ( error ) {
      console.log( { error: 'Error updating the post' } );
    }

    console.log( result.body );
  } ).catch( err => {
    console.log( err );
  } );
}
